"""adiciona watchlist

Revision ID: 746b7905f5d8
Revises: 0001_initial_movie_schema
Create Date: 2026-09-28 00:00:52.950454

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '746b7905f5d8'
down_revision: Union[str, Sequence[str], None] = '0001_initial_movie_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('sk_watchlist_id', sa.String(length=64), nullable=False),
    sa.Column('sk_movie_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sk_movie_id'], ['dim_movies.sk_movie_id'], name=op.f('fk_watchlist_sk_movie_id_dim_movies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sk_watchlist_id', name=op.f('pk_watchlist'))
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_sk_movie_id'), ['sk_movie_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_sk_movie_id'))

    op.drop_table('watchlist')
    # ### end Alembic commands ###
